# Generated by Django 4.1.6 on 2023-02-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='pago?')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantidade')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='preço')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ('order', 'pk'),
            },
        ),
    ]
