# Generated by Django 4.1.6 on 2023-02-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
