# Generated by Django 4.1.6 on 2023-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_cart_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='freight',
        ),
        migrations.AddField(
            model_name='cart',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='frete'),
        ),
    ]
